# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 600)
                MainWindow.setStyleSheet("background-color:rgb(0, 49, 53)")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                
                #Parte resultados
                self.resultadosButton = QtWidgets.QPushButton(self.centralwidget)
                self.resultadosButton.setGeometry(QtCore.QRect(170, 430, 75, 24))
                self.resultadosButton.setStyleSheet("""
        QPushButton {
                color: rgb(0, 0, 0);
                background-color: rgb(217, 217, 217);
                border-radius: 10px;
        }
        QPushButton:hover {
                background-color: rgb(180, 180, 180); /* Color más oscuro al pasar el mouse */
        }
        """)
                self.resultadosButton.setObjectName("resultadosButton")
                self.resultadosButton.clicked.connect(self.mostrar_resultados)
                
                
                #Parte errores
                self.erroresButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.erroresButton_2.setGeometry(QtCore.QRect(560, 430, 75, 24))
                font = QtGui.QFont()
                font.setFamily("Arial")
                self.erroresButton_2.setFont(font)
                self.erroresButton_2.setStyleSheet("""
    QPushButton {
        color: rgb(0, 0, 0);
        background-color: rgb(217, 217, 217);
        border-radius: 10px;
    }
    QPushButton:hover {
        background-color: rgb(180, 180, 180); /* Color más oscuro al pasar el mouse */
        cursor: pointer; /* Añade esta línea para el cursor de mano */
    }
""")
                self.erroresButton_2.setObjectName("erroresButton_2")
                self.erroresButton_2.clicked.connect(self.mostrar_errores)
                
                self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
                self.scrollArea.setGeometry(QtCore.QRect(50, 50, 701, 121))
                self.scrollArea.setStyleSheet("background-color: rgb(217, 217, 217);")
                self.scrollArea.setWidgetResizable(True)
                self.scrollArea.setObjectName("scrollArea")
                self.scrollAreaWidgetContents = QtWidgets.QWidget()
                self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 699, 119))
                self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
                self.scrollArea.setWidget(self.scrollAreaWidgetContents)
                self.salidaResultados = QtWidgets.QFrame(self.centralwidget)
                self.salidaResultados.setGeometry(QtCore.QRect(50, 220, 311, 191))
                self.salidaResultados.setStyleSheet("background-color: rgb(217, 217, 217);")
                self.salidaResultados.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.salidaResultados.setFrameShadow(QtWidgets.QFrame.Raised)
                self.salidaResultados.setObjectName("salidaResultados")
                self.salidaErrores = QtWidgets.QFrame(self.centralwidget)
                self.salidaErrores.setGeometry(QtCore.QRect(430, 220, 311, 191))
                self.salidaErrores.setStyleSheet("background-color: rgb(217, 217, 217);")
                self.salidaErrores.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.salidaErrores.setFrameShadow(QtWidgets.QFrame.Raised)
                self.salidaErrores.setObjectName("salidaErrores")
                self.textCodigo = QtWidgets.QLabel(self.centralwidget)
                self.textCodigo.setGeometry(QtCore.QRect(50, 20, 131, 20))
                self.textCodigo.setStyleSheet("color:rgb(255, 255, 255)")
                self.textCodigo.setObjectName("textCodigo")
                self.textResultados = QtWidgets.QLabel(self.centralwidget)
                self.textResultados.setGeometry(QtCore.QRect(50, 190, 131, 20))
                self.textResultados.setStyleSheet("color: rgb(255, 255, 255)")
                self.textResultados.setObjectName("textResultados")
                self.textErrores = QtWidgets.QLabel(self.centralwidget)
                self.textErrores.setGeometry(QtCore.QRect(430, 190, 131, 20))
                self.textErrores.setStyleSheet("color:rgb(255, 255, 255)")
                self.textErrores.setObjectName("textErrores")
                self.titulo = QtWidgets.QLabel(self.centralwidget)
                self.titulo.setGeometry(QtCore.QRect(230, 0, 431, 41))
                font = QtGui.QFont()
                font.setFamily("Arial Rounded MT")
                font.setPointSize(24)
                font.setBold(True)
                self.titulo.setFont(font)
                self.titulo.setStyleSheet("color: rgb(255, 255, 255);")
                self.titulo.setObjectName("titulo")
                self.titulo_2 = QtWidgets.QLabel(self.centralwidget)
                self.titulo_2.setGeometry(QtCore.QRect(650, 520, 141, 41))
                font = QtGui.QFont()
                font.setFamily("Arial Rounded MT")
                font.setPointSize(12)
                font.setBold(True)
                self.titulo_2.setFont(font)
                self.titulo_2.setStyleSheet("color: rgb(255, 255, 255);")
                self.titulo_2.setObjectName("titulo_2")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
                self.menubar.setObjectName("menubar")
                self.menuQue_es_esto = QtWidgets.QMenu(self.menubar)
                self.menuQue_es_esto.setObjectName("menuQue_es_esto")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)
                self.menubar.addAction(self.menuQue_es_esto.menuAction())

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)
        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Analizador Léxico"))
                self.resultadosButton.setText(_translate("MainWindow", "Resultados"))
                self.erroresButton_2.setText(_translate("MainWindow", "Errores"))
                self.textCodigo.setText(_translate("MainWindow", "Introduzca su código"))
                self.textResultados.setText(_translate("MainWindow", "Resultados"))
                self.textErrores.setText(_translate("MainWindow", "Errores"))
                self.titulo.setText(_translate("MainWindow", "Fase #1 Análisis Léxico"))
                self.titulo_2.setText(_translate("MainWindow", "Rodrigo Torres\n"
        "Jesús Araujo"))
                self.menuQue_es_esto.setTitle(_translate("MainWindow", "AnalisisLexico"))
                
        def mostrar_resultados(self):
                print("Botón 'Resultados' presionado")
                        
        def mostrar_errores(self):
                print("Botón 'Errores' presionado")


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
