# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prueba.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(106, 255, 118)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BotonPrueba = QtWidgets.QPushButton(self.centralwidget)
        self.BotonPrueba.setGeometry(QtCore.QRect(420, 400, 75, 24))
        self.BotonPrueba.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.BotonPrueba.setObjectName("BotonPrueba")
        self.TituloFCB = QtWidgets.QLabel(self.centralwidget)
        self.TituloFCB.setEnabled(True)
        self.TituloFCB.setGeometry(QtCore.QRect(210, 10, 451, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.TituloFCB.setFont(font)
        self.TituloFCB.setMouseTracking(False)
        self.TituloFCB.setTabletTracking(False)
        self.TituloFCB.setAutoFillBackground(False)
        self.TituloFCB.setStyleSheet("background-color: rgrgb(255, 255, 255)")
        self.TituloFCB.setScaledContents(False)
        self.TituloFCB.setAlignment(QtCore.Qt.AlignCenter)
        self.TituloFCB.setWordWrap(False)
        self.TituloFCB.setOpenExternalLinks(False)
        self.TituloFCB.setObjectName("TituloFCB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("Puedo cambiar esto?")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Hola", "Hola"))
        self.BotonPrueba.setText(_translate("MainWindow", "Prueba"))
        self.TituloFCB.setText(_translate("MainWindow", "FCB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
